### ISSUE TITLE
Add a new screen for visualize publication details

### ISSUE THREAD

**Issue by pixel-3092189** [From-Far-Away/SayIt#4]
This screen will be display when clicking on a publication list item. Following the current navigation method, the publication details must be developped in a new fragment. 
The scenario is the following : when clicking on a `ListView` item, a fragment transaction will replace the old fragment (for instance the publication screen) by the new one.

**Comment by Slals** [comment]
59fd7f7c2244c0a31733ba7f6ec283ff8df4e7d2 closes it
