### ISSUE TITLE
Binary data for audio

### ISSUE THREAD

**Issue by Slals** [From-Far-Away/SayIt#7]
As audio will be small file, I think the best way to manage them through HTTP while be to use their binary data.

I found a great [tutorial](http://www.survivingwithandroid.com/2013/06/android-apache-http-client.html) that shows how to do it.

Also I suggest to encode [the binary data in base64](http://stackoverflow.com/questions/4830711/how-to-convert-a-image-into-base64-string), because it's easier to manage for mongoose.

**Comment by pixel-3092189** [comment]
The `URLConnection` class has been used to build the current Android ItSaysClient (URLConnection seems to be a native Class of JAVA, and as well is usable in Android). 

`URLConnection` is naturally more low-level than Apache HTTP client (used in your tutorial), but for the consistency with the current code, it will be more efficient to use URLConnection (even if Apache Http Client would have been the better choice to start our ItSaysClient...).

An approach with the `URLConnection` is described in this [tutorial](http://www.codejava.net/java-se/networking/upload-files-by-sending-multipart-request-programmatically).
